"use client";

import "@/styles/globals.css";

import type { Metadata } from "next";

import { SessionProvider, useSession } from "next-auth/react";
import { redirect } from "next/navigation";
import React, { Suspense } from "react";
// import { wrapper } from "../redux/store";

type ContextProps = {
  defaultMode?: string;
  session?: any;
};

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME,
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export const Context = (props: React.PropsWithChildren<ContextProps>) => {
  return (
    <SessionProvider>
      <App {...props} />
    </SessionProvider>
  );
};

type AppProps = {
  defaultMode?: string;
  session?: any;
};

const App = (props: React.PropsWithChildren<AppProps>) => {
  const { status } = useSession();

  if (status === "unauthenticated") {
    redirect("/");
  }

  // if (status === "loading") {
  //   return <div className="min-h-screen">loading...</div>;
  // }

  return <Suspense>{props.children}</Suspense>;
};
